apiVersion: apps/v1
kind: Deployment
metadata:
  name: serverlab-besteffort
  namespace: serverlab
  labels:
    app: serverlab-besteffort
spec:
  replicas: 4
  selector:
    matchLabels:
      app: serverlab-besteffort
  template:
    metadata:
      labels:
        app: serverlab-besteffort
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
