apiVersion: apps/v1
kind: Deployment
metadata:
  name: serverlab-burst
  namespace: serverlab
  labels:
    app: serverlab-burst
spec:
  replicas: 4
  selector:
    matchLabels:
      app: serverlab-burst
  template:
    metadata:
      labels:
        app: serverlab-burst
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.05"
            memory: "32Mi"
          requests:
            cpu: "0.02"
            memory: "16Mi"