apiVersion: apps/v1
kind: Deployment
metadata:
  name: serverlab-nginx-sp
  namespace: serverlab-prod
  labels:
    app: serverlab-nginx-sp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: serverlab-nginx-sp
  template:
    metadata:
      labels:
        app: serverlab-nginx-sp
    spec:
      priorityClassName: standard-priority
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.05"
            memory: "128Mi"
          requests:
            cpu: "0.02"
            memory: "64Mi"