apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo1
  name: demo1
  namespace: serverlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo1
  template:
    metadata:
      labels:
        app: demo1
    spec:
      containers:
      - name: nginx
        image: nginx
      - name: sidecar
        image: ubuntu
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo hello; sleep 120;done"]