apiVersion: v1
kind: ResourceQuota
metadata:
  name: pods-cluster-services
  namespace: app1
spec:
  scopeSelector:
    matchExpressions:
      - operator : In
        scopeName: PriorityClass
        values: ["cluster-services"]