apiVersion: v1
kind: LimitRange
metadata:
  name: core-limits
  namespace: serverlab
spec:
  limits:
  - type: Pod
    max:
      cpu: "1.0"
      memory: "1Gi"
  - type: Container
    max:
      cpu: "800m"